### ISSUE TITLE
Add in the menu menu the option About

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ux#10]
Currently the main navigation system has the following options:

- Home
- Projects
- Docs
- Articles

**After:**

- Home
- About
- Projects
- Docs
- Articles

**Comment by Suriv** [comment]
It would not be better:


- Home
- Projects
- Docs
- Articles
- About

**Comment by jabrena** [comment]
For this release, we will skip articles:

-     Home
-     Projects
-     Docs
-     About
