### ISSUE TITLE
Add .ico

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ux#8]
Ico:
https://slack-imgs.com/?c=1&o1=wi16.he16.si&url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F856944057481908226%2FOSHowvVA_normal.jpg

**Comment by Suriv** [comment]
The change done.

Reference icon a: "A project to learn Java and create software for Mindstorms Robots using EV3Dev & the LeJOS way."

**Comment by jabrena** [comment]
It is necessary to replace the icon with the original one:
http://ev3dev-lang-java.github.io/Media/Images/icon.png

The icon represent ROS logo. This project is an ROS application over Lego Mindstorms ecosystem.
